version: '3.8'

services:
  shared_expenses_service:
      build:
        context: ./SharedExpensesService
      container_name: shared_expenses_service
      ports:
        - "8004:8004"
      env_file:
        - ./SharedExpensesService/.env
      volumes:
        - ./common:/common/common
        - ./SharedExpensesService:/app
      environment:
        - PYTHONPATH=/app:/common
      depends_on:
        - db
  
  db:
    image: postgres:15
    container_name: finance_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql  # Load schema creation script

volumes:
  db_data: