version: '3.8'

services:
  user_login_service:
    build:
      context: ./UserLoginService
    container_name: user_login_service
    ports:
      - "8002:8002"
    env_file:
      - ./UserLoginService/.env
    volumes:
      - ./UserLoginService:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: