version: '3.8'

services:
  transaction_analysis_service:
    build:
      context: ./TransactionAnalysisService
    container_name: transaction_analysis_service
    ports:
      - "8003:8003"
    env_file:
      - ./TransactionAnalysisService/.env
    volumes:
      - ./TransactionAnalysisService:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
