version: '3.8'

services:
  # user_login_service:
  #   build:
  #     context: ./UserLoginService
  #   container_name: user_login_service
  #   ports:
  #     - "8002:8002"
  #   env_file:
  #     - ./UserLoginService/.env
  #   volumes:
  #     - ./UserLoginService:/app
  #   depends_on:
  #     - db

  expense_management_service:
    build:
      context: ./ExpenseManagement
    container_name: expense_management_service
    ports:
      - "8005:8005"
    env_file:
      - ./ExpenseManagement/.env
    volumes:
      - ./ExpenseManagement:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data: