USER_ROLES = "user"
AUTH_SERVICE_ROLE = "auth_service"
USER_SERVICE_ROLE = "user_service"
BUDGETING_SERVICE_ROLE = "budgeting_service"
EXPENSE_MANAGEMENT_SERVICE_ROLE = "expense_management_service"
SHARED_EXPENSES_SERVICE_ROLE = "shared_expenses_service"

TRANSACTION_SERVICE_URL="http://expense_management_service:8005"
BUDGETING_SERVICE_URL="http://budgeting_service:8003"
USER_LOGIN_SERVICE_URL="http://user_login_service:8002/api/v1/user"
